apiVersion: v1
kind: Secret
metadata:
    name: environment-bb
stringData:
    values.yaml: ENC[AES256_GCM,data:NljTOJZECQ6kCg==,iv:Tl2VZmgSS7qEbD54TAEKUdC3hEtNEbbLHbeFTFp71kM=,tag:30Kg4V3upGNyyuk0PNApGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-01-29T20:46:03Z'
    mac: ENC[AES256_GCM,data:yIuIikLkw7aC7Z/SaE4cT7ntBt5po+AFuHoh1HU5gop4hiy4F90vM9DQu0Bayy8a74z/u7shJuefHvX5qRW9Ib4YTClWPGRzu8Asi4dwGhwK/drDjma7h8IFMD3qKG+ren7st5hrNx7zpuVFm5xsTe5ywFna36Tyain/bmqfKQE=,iv:Qi/Wx3WUluNNPQyLxG+mbS7cEAm1eTD66RXT/1Joq1E=,tag:UxMbUAJLsdHD1C5mE4mNzA==,type:str]
    pgp:
    -   created_at: '2021-02-17T19:23:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4w8TIDDcZH4ARAAl8CEmjG60gX3vPFRnSjvvSqV5ufbb6JivkQtHxQuPEpw
            U+RUKhV1qL+X7P87YyxN0Ywr+Ws2CTvcgIIWQtOe/TtdF72wnw6NBwPUxsT08SSY
            bBwI1wQmv/S67hdr3ezWahcctRaHgM37bTlFbr2ebEsrn3azx+WLtsueKQWdJzft
            RYrMVHqlqDbjBGHei0XYh+URaOGh3ENDzygzEgc3Uzih9LVG5/ZNL0HChu1SOqVc
            97WW+U33m7yThbK9Bni4POZXCC5JEQID6NT91XnvlqAQf1gtitOzIRUWBGU4sk1N
            2fwVwO2QNB/48HsKR+uFUw/U96gB117DLwDHukbdtPo7LdNjyKCl7D0e4g5hcZ5m
            KmVaHkxfRra9d0O8Rjl43e+iNramALImNb/CPZMlGruA/nizGHPiNWtbzHowxX4Z
            Q4Lm26xL5RLG/GX7MILTHfcFIoaveRtNKVxQk4N9cRThhJyGqHqIGyK4j2yYM0JB
            bU8Y+Fi11u876+XqaNdh51qRaEg36D1GgepPU9UerVm8p00KabczIumKG8qeMlem
            Crm+BAmCMKYN4ZolkqQDTrazu9860gvanZTDroVkK18gRXPqh8gPMFa744VzNwqI
            XI0gVMDxOt3/ilCt1ivkE3LgWf1RgWAkIYhq6i4SLzJKvsqraNY36y4XyDYueZXS
            XAHAYiyYnbl4QXeINvKX98BMOk1KeO682+lDvzVhnasQTVdvaEaDjuiLhwXn6ZnD
            jt2hTkffLykD0zQhcbbBhjYgiC1502PA5Np3I/M9s28CI6CX7AZ7W/Kz1N8t
            =tK4c
            -----END PGP MESSAGE-----
        fp: 56F321E5DCDC2C295D0BA826037693B6007B0DB5
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
